### PR TITLE
parse @throws like @return and @param in the docblock

### LINKED ISSUE #53: Domain exceptions are not imported correctly
Say you have the following entity:

```php
<?php

namespace Loevgaard\HostnetTest\Entity;

use Doctrine\ORM\Mapping as ORM;
use Loevgaard\HostnetTest\Entity\Generated\EntityInterface;
use Loevgaard\HostnetTest\Entity\Generated\EntityTrait;
use Loevgaard\HostnetTest\Exception\AnotherDomainException;
use Loevgaard\HostnetTest\Exception\DomainException;

/**
 * @ORM\Entity()
 **/
class Entity implements EntityInterface
{
    use EntityTrait;

    /**
     * @throws \InvalidArgumentException
     */
    public function throwInvalidArgumentException()
    {
        throw new \InvalidArgumentException('Testing');
    }

    /**
     * @throws DomainException
     */
    public function throwDomainException()
    {
        throw new DomainException('Testing');
    }

    /**
     * @throws \Loevgaard\HostnetTest\Exception\AnotherDomainException
     */
    public function throwAnotherDomainException()
    {
        throw new AnotherDomainException('Testing');
    }
}

```

This generates the following interface:

```php
<?php
namespace Loevgaard\HostnetTest\Entity\Generated;

/**
 * Implement this interface in Entity!
 * This is a combined interface that will automatically extend to contain the required functions.
 */
interface EntityInterface
{

    /**
     * @throws \InvalidArgumentException
     */
    public function throwInvalidArgumentException();

    /**
     * @throws DomainException
     */
    public function throwDomainException();

    /**
     * @throws \Loevgaard\HostnetTest\Exception\AnotherDomainException
     */
    public function throwAnotherDomainException();
}
```

which is wrong since the method `throwDomainException()` should have a phpdoc `@throws` statement that said: `@throws \Loevgaard\HostnetTest\Exception\DomainException`.

I have created a repos for the issue here: https://github.com/loevgaard/hostnet-test if you want to see it in action.

### PR DESCRIPTION
**Pull request by svandervlugt**
fixes #53

### CODE REVIEW

File: src/ReflectionMethod.php [hunk 1]
```diff
@@ -115,9 +115,9 @@ private function processDocMatch(array $matches)
      */
     private function qualifyType($type)
     {
-        // "Type" is a variable, i.e. $this.
-        if ('$' === $type[0]) {
-            return $type;
+       // "Type" is a variable, i.e. $this.
```
Comment (yannickl88) [inline src/ReflectionMethod.php]: please put the whitespaces back

File: test/Functional/src/Exception/AnotherDomainException.php [hunk 2]
```diff
@@ -0,0 +1,10 @@
+<?php
+
```
Comment (yannickl88) [inline test/Functional/src/Exception/AnotherDomainException.php]: rm empty lines

File: test/Functional/src/Exception/DomainException.php [hunk 3]
```diff
@@ -0,0 +1,10 @@
+<?php
+
```
Comment (yannickl88) [inline test/Functional/src/Exception/DomainException.php]: same
